nelmio_api_doc:
    documentation:
        info:
            title: Project Management API
            description: API REST Symfony
            version: 1.0.0

        
        tags:
            - name: Authentication
              description: Authentication endpoints
            - name: Employees
              description: Employee management
            - name: Projects
              description: Project management
            - name: Tasks
              description: Task management

        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT

        security:
            - Bearer: []

        paths:
            /api/login_check:
                post:
                    tags:
                        - Authentication
                    summary: Login JWT
                    security: []
                    requestBody:
                        required: true
                        content:
                            application/json:
                                schema:
                                    type: object
                                    properties:
                                        email:
                                            type: string
                                            example: admin@test.com
                                        password:
                                            type: string
                                            example: Aabc123
                    responses:
                        '200':
                            description: JWT token generated
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            token:
                                                type: string
                        '401':
                            description: Invalid credentials

    areas:
        path_patterns:
            - ^/api